# Generated by Django 6.0.5 on 2026-05-13 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_l2server'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
    ]
